package com.persona.config;

import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;
import org.springframework.security.crypto.password.PasswordEncoder;

/**
 * Supplies the one security-related bean Day-05 needs: a password encoder.
 *
 * <p><b>This class does not enable Spring Security.</b> The name is chosen
 * because Day-06 will grow it, but today the project depends on
 * {@code spring-security-crypto} only — a plain library with no filters, no
 * auto-configuration and no effect on any endpoint. Adding
 * {@code spring-boot-starter-security} instead would install a
 * {@code SecurityFilterChain} that locks every URL behind a login form that
 * does not exist yet, turn all 30 existing tests red, and print a generated
 * password into the startup log. A dependency is not free because it compiles.
 *
 * <h2>Why a @Configuration class rather than a field in UserService</h2>
 *
 * <p>{@code new BCryptPasswordEncoder()} inside the service would work and is
 * what the shorter tutorials do. Three things are bought by declaring it as a
 * bean instead:
 *
 * <ul>
 *   <li><b>The cost factor is decided in one place.</b> It is a tuning
 *       parameter that will change as hardware gets faster, and a value
 *       scattered across call sites drifts.</li>
 *   <li><b>The service depends on the interface.</b> {@code UserService} takes
 *       {@link PasswordEncoder}, not {@code BCryptPasswordEncoder}, so a move
 *       to argon2 is an edit to this file alone — the same reason Day-03
 *       extracted {@code UserRepository} before a second implementation
 *       existed.</li>
 *   <li><b>Tests can substitute a fast one.</b> Which matters more than it
 *       sounds; see below.</li>
 * </ul>
 */
@Configuration
public class SecurityConfig {

    /**
     * BCrypt at the library default cost of 10.
     *
     * <h2>Why the algorithm is deliberately slow</h2>
     *
     * <p>Every other decision in this project made something faster. This one
     * makes something slow on purpose, and the slowness <em>is</em> the
     * security.
     *
     * <p>An attacker who steals the {@code users} table does not attack the
     * algorithm; they guess. On a consumer GPU, SHA-256 runs at roughly ten
     * billion hashes per second, so the ten million most common passwords can
     * be tried against an entire table in well under a second. BCrypt at cost
     * 10 runs at roughly ten thousand per second, and the same list takes weeks
     * <em>per password</em>.
     *
     * <p>SHA-256 is not a bad hash — it is a bad <em>password</em> hash,
     * because it was designed to be fast, which is exactly right for checksums
     * and exactly wrong here.
     *
     * <pre>
     *   cost 10  ->  2^10 = 1024 rounds   ~  50-100 ms
     *   cost 11  ->  2^11 = 2048 rounds   ~ 100-200 ms
     *   cost 12  ->  2^12 = 4096 rounds   ~ 200-400 ms
     * </pre>
     *
     * <p>Each increment <b>doubles</b> the work: unnoticeable to one person
     * logging in, devastating to someone doing it ten billion times. Hardware
     * gets faster every year and BCrypt has a dial to compensate. <b>That dial
     * is the feature</b>, and SHA-256 does not have one.
     *
     * <h2>Salt, and why it is not a secret</h2>
     *
     * <p>Two users with the same password must not produce the same digest, or
     * an attacker who spots the collision has cracked two accounts for one
     * guess, and precomputed rainbow tables crack the whole column at once. A
     * salt is random bytes mixed in before hashing, unique per row.
     *
     * <p>The salt is stored in plaintext, inside the hash string itself. That
     * feels wrong and is not: its only job is to stop work being shared between
     * rows, and it does that whether or not the attacker can read it.
     *
     * <pre>
     *   $2a$10$N9qo8uLOickgx2ZMRZoMye IjZAgcfl7p92ldGxad68LJZdL17lhWy
     *    |   |  |                      |
     *    |   |  +- salt, 22 chars      +- hash, 31 chars
     *    |   +---- cost factor
     *    +-------- algorithm version
     *
     *   One string. Always exactly 60 characters -> VARCHAR(60) in V2.
     * </pre>
     *
     * <p>There is no {@code salt} column and no salt is generated by hand.
     * Note also that the <em>cost factor is stored in the output</em>, which is
     * what lets the cost be raised later without invalidating existing hashes:
     * {@code matches} reads the cost out of the stored string rather than
     * assuming the current setting.
     *
     * <h2>The two methods, and the test everyone gets wrong</h2>
     *
     * <pre>
     *   encode(raw)            -> a NEW hash, DIFFERENT on every call
     *   matches(raw, stored)   -> reads salt + cost out of `stored`,
     *                             re-hashes `raw` the same way, compares
     * </pre>
     *
     * <p>{@code encode(x).equals(encode(x))} is <b>false</b>, always, because
     * each call draws a new random salt. This is correct behaviour and it is
     * the first test most people write and cannot explain. Comparison is done
     * with {@code matches}, never with {@code equals}.
     *
     * <h2>The cost of the cost factor, in the test suite</h2>
     *
     * <p>Cost 10 is ~50-100ms per hash. A suite that registers a user in thirty
     * tests pays three seconds for it. That is tolerable now and is the kind of
     * thing that quietly becomes a two-minute suite by Day-14.
     *
     * <p>Left at the default deliberately, because the alternative — lowering
     * the cost in tests — means the tests no longer exercise the configuration
     * that ships. Recorded as dated debt: if the suite becomes slow, the fix is
     * a test-profile bean at cost 4, and the thing to check when doing it is
     * that at least one test still runs at the production cost.
     */
    @Bean
    public PasswordEncoder passwordEncoder() {
        return new BCryptPasswordEncoder();
    }
}
